<a href="https://colab.research.google.com/github/ancestor9/24_fall_Big-Data-Processing-coding-/blob/main/01_bigdata_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.  파일 불러오기

# 데이터 분석의 구체적인 순서

1. ## 문제 정의 (Problem Definition)
    - **목표 설정**: 해결하고자 하는 비즈니스 문제나 분석의 목표를 명확히 정의합니다. 예: 판매량 예측, 고객 이탈 분석 등.
    - **성공 기준 설정**: 성공적인 분석의 기준을 설정합니다. 예: 정확도, 비용 절감, 시간 효율성 등.

2. ## 데이터 수집 (Data Collection)
    - **데이터 소스 결정**: 분석에 필요한 데이터를 수집할 소스를 결정합니다. 예: 내부 데이터베이스, 웹 스크래핑, 공개된 데이터셋 등.
    - **데이터 획득**: SQL, API, 크롤링 등 다양한 방법을 사용하여 데이터를 수집합니다.

3. ## 데이터 전처리 (Data Preprocessing)
    - **데이터 정리**: 결측값, 이상값을 처리하고 데이터를 정리합니다.
    - **데이터 통합**: 여러 소스에서 수집된 데이터를 통합합니다.
    - **데이터 변환**: 필요한 경우 스케일링, 원핫 인코딩, 로그 변환 등 데이터를 변환하여 모델에 적합한 형태로 만듭니다.

4. ## 탐색적 데이터 분석 (Exploratory Data Analysis, EDA)
    - **데이터 시각화**: 히스토그램, 상자 그림(Boxplot), 산점도(Scatter plot) 등을 사용하여 데이터를 시각적으로 탐색합니다.
    - **통계 분석**: 기초 통계량(평균, 중앙값, 분산 등)을 계산하고 데이터의 특성을 이해합니다.
    - **변수 간 상관관계 분석**: 변수 간의 상관관계, 패턴 등을 탐색합니다.

5. ## 특징 추출 및 선택 (Feature Engineering and Selection)
    - **새로운 특징 생성**: 기존 데이터에서 의미 있는 새로운 특징을 생성합니다.
    - **특징 선택**: 불필요하거나 상관관계가 낮은 특징을 제거하고, 중요한 특징만 선택하여 모델의 성능을 향상시킵니다.

6. ## 모델 선택 및 학습 (Model Selection and Training)
    - **모델 선택**: 분석 목표에 따라 적절한 모델(예: 선형 회귀, 의사결정 트리, 랜덤 포레스트, 신경망 등)을 선택합니다.
    - **모델 학습**: 훈련 데이터를 사용하여 선택한 모델을 학습시킵니다.

7. ## 모델 평가 (Model Evaluation)
    - **성능 평가**: 테스트 데이터를 사용하여 모델의 성능을 평가합니다. 정확도, 정밀도, 재현율, F1 스코어, AUC 등 다양한 평가 지표를 사용합니다.
    - **모델 튜닝**: 하이퍼파라미터 튜닝, 교차 검증 등을 통해 모델 성능을 최적화합니다.

8. ## 결과 해석 및 시각화 (Interpretation and Visualization)
    - **결과 해석**: 모델의 예측 결과를 비즈니스 측면에서 해석합니다.
    - **시각화**: 중요한 결과를 시각화하여 의사 결정자나 이해 관계자에게 쉽게 전달할 수 있도록 합니다.

9. ## 결론 도출 및 의사 결정 (Conclusion and Decision Making)
    - **인사이트 도출**: 분석 결과로부터 의미 있는 인사이트를 도출합니다.
    - **비즈니스 의사 결정**: 도출된 인사이트를 바탕으로 비즈니스 의사 결정을 내립니다.

10. ## 보고서 작성 및 공유 (Reporting and Sharing)
    - **보고서 작성**: 분석 과정과 결과를 포함한 보고서를 작성하여 공유합니다.
    - **피드백 반영**: 필요에 따라 추가 분석이나 모델 개선을 진행합니다.

In [ ]:
# prompt: Dir 데렉토리를 만들어줘

!mkdir Dir

In [ ]:
# prompt: os 모듈을 사용하여 Dir 디렉토리를 만들어줘

import os

if not os.path.exists('Dir'):
  os.makedirs('Dir')

In [ ]:
# prompt: Dir 디렉토리 아래 Dir1, Dir 2 디ꂌㄱ토리를 만들어줘

import os

if not os.path.exists('Dir/Dir1'):
  os.makedirs('Dir/Dir1')

if not os.path.exists('Dir/Dir2'):
  os.makedirs('Dir/Dir2')

In [ ]:
# prompt: Dir 1 에  이름과 나이를 속성으로 갖고 먹고 배고프다라는 method를 갖는 Person class를 만들어줘

%%writefile Dir/Dir1/Person.py
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def eat(self):
    print("먹고")

  def hungry(self):
    print("배고프다")

Writing Dir/Dir1/Person.py

In [ ]:
# prompt: Dir 1에 Person class를 호출하여 eat를 실행하는 main.py를 만들어줘

%%writefile Dir/Dir1/main.py
from Person import Person

person = Person("John Doe", 30)
person.eat()

Writing Dir/Dir1/main.py

In [ ]:
# prompt: main.py를 실행해줘

!python Dir/Dir1/main.py

먹고

In [ ]:
%%writefile Dir/Dir1/Person.py
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def eat(self):
    print("먹고")

  def hungry(self):
    print("배고프다")

class Student(Person):
  def __init__(self, name, age, student_id):
    super().__init__(name, age)
    self.student_id = student_id

  def study(self):
    print("공부하고")

class Teacher(Person):
  def __init__(self, name, age, subject):
    super().__init__(name, age)
    self.subject = subject

  def teach(self):
    print("강사하고")

Overwriting Dir/Dir1/Person.py

In [ ]:
import Dir.Dir1.Person as Person

In [ ]:
human = Person.Person('ancestor9', 20)
human.eat()

먹고

In [ ]:
s1 = Person.Student('ancestor9', 20, 1)
s1.study()

공부하고

In [ ]:
import Dir

In [ ]:
import Dir.Dir1.Person as Person

In [ ]:
from Dir.Dir1.Person import Person

In [ ]:
# prompt: Dir 디렉토리를 삭제

!rm -rf Dir

In [ ]:
# prompt: 노트북 셀내 여러 명령어의 출력을 다 출력해줘

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
# prompt: list, dict, numpy로 데이터프레임을 만드는 예제 코드를 부탁해, print문은사용하지 마시고 그냥 보여줘

import pandas as pd

# 리스트를 사용하여 DataFrame 생성
data_list = [
    ['apple', 10],
    ['banana', 20],
    ['orange', 30]
]
df_list = pd.DataFrame(data_list, columns=['Fruit', 'Count'])



# 딕셔너리를 사용하여 DataFrame 생성
data_dict = {
    'Fruit': ['apple', 'banana', 'orange'],
    'Count': [10, 20, 30]
}
df_dict = pd.DataFrame(data_dict)


# NumPy 배열을 사용하여 DataFrame 생성
import numpy as np
data_np = np.array([
    ['apple', 10],
    ['banana', 20],
    ['orange', 30]
])
df_np = pd.DataFrame(data_np, columns=['Fruit', 'Count'])

df_list
df_dict
df_np

    Fruit  Count
0   apple     10
1  banana     20
2  orange     30

    Fruit  Count
0   apple     10
1  banana     20
2  orange     30

    Fruit Count
0   apple    10
1  banana    20
2  orange    30

In [ ]:
# prompt: https://github.com/microsoft/powerbi-desktop-samples/blob/main/AdventureWorks%20Sales%20Sample/AdventureWorks%20Sales.xlsx 파일은 여러 시트로 구성되어 있는데 모든 시트를 읽어줘

import pandas as pd

#!pip install pandas openpyxl


# Replace with the actual URL of your Excel file
url = "https://github.com/microsoft/powerbi-desktop-samples/raw/main/AdventureWorks%20Sales%20Sample/AdventureWorks%20Sales.xlsx"

try:
  xls = pd.ExcelFile(url)
  sheet_names = xls.sheet_names

  all_sheets_data = {}
  for sheet_name in sheet_names:
    df = pd.read_excel(url, sheet_name=sheet_name)
    print(df.head())
    all_sheets_data[sheet_name] = df
    print(f"Sheet '{sheet_name}' loaded successfully.")

except Exception as e:
  print(f"Error loading Excel file: {e}")

    Channel  SalesOrderLineKey Sales Order Sales Order Line
0  Reseller           43659001     SO43659      SO43659 - 1
1  Reseller           43659002     SO43659      SO43659 - 2
2  Reseller           43659003     SO43659      SO43659 - 3
3  Reseller           43659004     SO43659      SO43659 - 4
4  Reseller           43659005     SO43659      SO43659 - 5
Sheet 'Sales Order_data' loaded successfully.
   SalesTerritoryKey     Region        Country          Group
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
2                  3    Central  United States  North America
3                  4  Southwest  United States  North America
4                  5  Southeast  United States  North America
Sheet 'Sales Territory_data' loaded successfully.
   SalesOrderLineKey  ResellerKey  CustomerKey  ProductKey  OrderDateKey  \
0           43659001          676           -1         349      20170702
1           43659002          676           -1         350      20170702
2           43659003          676           -1         351      20170702
3           43659004          676           -1         344      20170702
4           43659005          676           -1         345      20170702

   DueDateKey  ShipDateKey  SalesTerritoryKey  Order Quantity  Unit Price  \
0    20170712   20170709.0                  5               1    2024.994
1    20170712   20170709.0                  5               3    2024.994
2    20170712   20170709.0                  5               1    2024.994
3    20170712   20170709.0                  5               1    2039.994
4    20170712   20170709.0                  5               1    2039.994

   Extended Amount  Unit Price Discount Pct  Product Standard Cost  \
0         2024.994                        0              1898.0944
1         6074.982                        0              1898.0944
2         2024.994                        0              1898.0944
3         2039.994                        0              1912.1544
4         2039.994                        0              1912.1544

   Total Product Cost  Sales Amount
0           1898.0944      2024.994
1           5694.2832      6074.982
2           1898.0944      2024.994
3           1912.1544      2039.994
4           1912.1544      2039.994
Sheet 'Sales_data' loaded successfully.
   ResellerKey       Reseller ID         Business Type  \
0           -1  [Not Applicable]      [Not Applicable]
1            1        AW00000001  Value Added Reseller
2            2        AW00000002   Specialty Bike Shop
3            3        AW00000003             Warehouse
4            4        AW00000004  Value Added Reseller

                   Reseller              City    State-Province  \
0          [Not Applicable]  [Not Applicable]  [Not Applicable]
1              A Bike Store           Seattle        Washington
2        Progressive Sports            Renton        Washington
3  Advanced Bike Components            Irving             Texas
4     Modular Cycle Systems            Austin             Texas

     Country-Region       Postal Code
0  [Not Applicable]  [Not Applicable]
1     United States             98104
2     United States             98055
3     United States             75061
4     United States             78701
Sheet 'Reseller_data' loaded successfully.
    DateKey       Date Fiscal Year Fiscal Quarter     Month     Full Date  \
0  20170701 2017-07-01      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 01
1  20170702 2017-07-02      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 02
2  20170703 2017-07-03      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 03
3  20170704 2017-07-04      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 04
4  20170705 2017-07-05      FY2018      FY2018 Q1  2017 Jul  2017 Jul, 05

   MonthKey
0    201707
1    201707
2    201707
3    201707
4    201707
Sheet 'Date_data' loaded successfully.
   ProductKey         SKU                    Product  Standard Cost  Color  \
0         210  FR-R92B-58  HL Road Frame - Black, 58       868.6342  Black
1         211  FR-R92R-58    HL Road Frame - Red, 58       868.6342    Red
2         212   HL-U509-R      Sport-100 Helmet, Red        12.0278    Red
3         213   HL-U509-R      Sport-100 Helmet, Red        13.8782    Red
4         214   HL-U509-R      Sport-100 Helmet, Red        13.0863    Red

   List Price          Model  Subcategory     Category
0   1431.5000  HL Road Frame  Road Frames   Components
1   1431.5000  HL Road Frame  Road Frames   Components
2     33.6442      Sport-100      Helmets  Accessories
3     33.6442      Sport-100      Helmets  Accessories
4     34.9900      Sport-100      Helmets  Accessories
Sheet 'Product_data' loaded successfully.
   CustomerKey       Customer ID          Customer              City  \
0           -1  [Not Applicable]  [Not Applicable]  [Not Applicable]
1        11000        AW00011000          Jon Yang       Rockhampton
2        11001        AW00011001      Eugene Huang           Seaford
3        11002        AW00011002      Ruben Torres            Hobart
4        11003        AW00011003       Christy Zhu        North Ryde

     State-Province    Country-Region       Postal Code
0  [Not Applicable]  [Not Applicable]  [Not Applicable]
1        Queensland         Australia              4700
2          Victoria         Australia              3198
3          Tasmania         Australia              7001
4   New South Wales         Australia              2113
Sheet 'Customer_data' loaded successfully.

In [ ]:
all_sheets_data.keys()

dict_keys(['Sales Order_data', 'Sales Territory_data', 'Sales_data', 'Reseller_data', 'Date_data', 'Product_data', 'Customer_data'])

In [ ]:
# prompt: all_sheets_data의 key에 해당되는 데이터프래임 크기를 모두 확인하려면

for key, df in all_sheets_data.items():
  print(f"DataFrame '{key}' shape: {df.shape}")
  df.head()
  print('*'*100)

DataFrame 'Sales Order_data' shape: (121253, 4)

    Channel  SalesOrderLineKey Sales Order Sales Order Line
0  Reseller           43659001     SO43659      SO43659 - 1
1  Reseller           43659002     SO43659      SO43659 - 2
2  Reseller           43659003     SO43659      SO43659 - 3
3  Reseller           43659004     SO43659      SO43659 - 4
4  Reseller           43659005     SO43659      SO43659 - 5

****************************************************************************************************
DataFrame 'Sales Territory_data' shape: (11, 4)

   SalesTerritoryKey     Region        Country          Group
0                  1  Northwest  United States  North America
1                  2  Northeast  United States  North America
2                  3    Central  United States  North America
3                  4  Southwest  United States  North America
4                  5  Southeast  United States  North America

****************************************************************************************************
DataFrame 'Sales_data' shape: (121253, 15)

,SalesOrderLineKey,ResellerKey,CustomerKey,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,SalesTerritoryKey,Order Quantity,Unit Price,Extended Amount,Unit Price Discount Pct,Product Standard Cost,Total Product Cost,Sales Amount
0,43659001,676,-1,349,20170702,20170712,20170709.0,5,1,2024.994,2024.994,0,1898.0944,1898.0944,2024.994
1,43659002,676,-1,350,20170702,20170712,20170709.0,5,3,2024.994,6074.982,0,1898.0944,5694.2832,6074.982
2,43659003,676,-1,351,20170702,20170712,20170709.0,5,1,2024.994,2024.994,0,1898.0944,1898.0944,2024.994
3,43659004,676,-1,344,20170702,20170712,20170709.0,5,1,2039.994,2039.994,0,1912.1544,1912.1544,2039.994
4,43659005,676,-1,345,20170702,20170712,20170709.0,5,1,2039.994,2039.994,0,1912.1544,1912.1544,2039.994

****************************************************************************************************
DataFrame 'Reseller_data' shape: (702, 8)

,ResellerKey,Reseller ID,Business Type,Reseller,City,State-Province,Country-Region,Postal Code
0,-1,[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable]
1,1,AW00000001,Value Added Reseller,A Bike Store,Seattle,Washington,United States,98104
2,2,AW00000002,Specialty Bike Shop,Progressive Sports,Renton,Washington,United States,98055
3,3,AW00000003,Warehouse,Advanced Bike Components,Irving,Texas,United States,75061
4,4,AW00000004,Value Added Reseller,Modular Cycle Systems,Austin,Texas,United States,78701

****************************************************************************************************
DataFrame 'Date_data' shape: (1461, 7)

,DateKey,Date,Fiscal Year,Fiscal Quarter,Month,Full Date,MonthKey
0,20170701,2017-07-01,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 01",201707
1,20170702,2017-07-02,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 02",201707
2,20170703,2017-07-03,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 03",201707
3,20170704,2017-07-04,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 04",201707
4,20170705,2017-07-05,FY2018,FY2018 Q1,2017 Jul,"2017 Jul, 05",201707

****************************************************************************************************
DataFrame 'Product_data' shape: (397, 9)

,ProductKey,SKU,Product,Standard Cost,Color,List Price,Model,Subcategory,Category
0,210,FR-R92B-58,"HL Road Frame - Black, 58",868.6342,Black,1431.5000,HL Road Frame,Road Frames,Components
1,211,FR-R92R-58,"HL Road Frame - Red, 58",868.6342,Red,1431.5000,HL Road Frame,Road Frames,Components
2,212,HL-U509-R,"Sport-100 Helmet, Red",12.0278,Red,33.6442,Sport-100,Helmets,Accessories
3,213,HL-U509-R,"Sport-100 Helmet, Red",13.8782,Red,33.6442,Sport-100,Helmets,Accessories
4,214,HL-U509-R,"Sport-100 Helmet, Red",13.0863,Red,34.9900,Sport-100,Helmets,Accessories

****************************************************************************************************
DataFrame 'Customer_data' shape: (18485, 7)

,CustomerKey,Customer ID,Customer,City,State-Province,Country-Region,Postal Code
0,-1,[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable]
1,11000,AW00011000,Jon Yang,Rockhampton,Queensland,Australia,4700
2,11001,AW00011001,Eugene Huang,Seaford,Victoria,Australia,3198
3,11002,AW00011002,Ruben Torres,Hobart,Tasmania,Australia,7001
4,11003,AW00011003,Christy Zhu,North Ryde,New South Wales,Australia,2113

****************************************************************************************************

In [ ]:
df = all_sheets_data['Customer_data']
df

,CustomerKey,Customer ID,Customer,City,State-Province,Country-Region,Postal Code
0,-1,[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable],[Not Applicable]
1,11000,AW00011000,Jon Yang,Rockhampton,Queensland,Australia,4700
2,11001,AW00011001,Eugene Huang,Seaford,Victoria,Australia,3198
3,11002,AW00011002,Ruben Torres,Hobart,Tasmania,Australia,7001
4,11003,AW00011003,Christy Zhu,North Ryde,New South Wales,Australia,2113
...,...,...,...,...,...,...,...
18480,29479,AW00029479,Tommy Tang,Versailles,Yveline,France,78000
18481,29480,AW00029480,Nina Raji,London,England,United Kingdom,SW19 3RU
18482,29481,AW00029481,Ivan Suri,Hof,Bayern,Germany,95010
18483,29482,AW00029482,Clayton Zhang,Saint Ouen,Charente-Maritime,France,17490
18484,29483,AW00029483,Jésus Navarro,Paris La Defense,Hauts de Seine,France,92081

In [ ]:
# prompt: df의 첫번째 줄은 삭제해주세요

df = df.iloc[1:]
df

,CustomerKey,Customer ID,Customer,City,State-Province,Country-Region,Postal Code
1,11000,AW00011000,Jon Yang,Rockhampton,Queensland,Australia,4700
2,11001,AW00011001,Eugene Huang,Seaford,Victoria,Australia,3198
3,11002,AW00011002,Ruben Torres,Hobart,Tasmania,Australia,7001
4,11003,AW00011003,Christy Zhu,North Ryde,New South Wales,Australia,2113
5,11004,AW00011004,Elizabeth Johnson,Wollongong,New South Wales,Australia,2500
...,...,...,...,...,...,...,...
18480,29479,AW00029479,Tommy Tang,Versailles,Yveline,France,78000
18481,29480,AW00029480,Nina Raji,London,England,United Kingdom,SW19 3RU
18482,29481,AW00029481,Ivan Suri,Hof,Bayern,Germany,95010
18483,29482,AW00029482,Clayton Zhang,Saint Ouen,Charente-Maritime,France,17490
18484,29483,AW00029483,Jésus Navarro,Paris La Defense,Hauts de Seine,France,92081

In [ ]:
# prompt: 'ancestor9' 디렉토리를 만들고 pickle 팡일로 저장하려고 한다

import os
import pickle

# 디렉토리 생성
directory = 'ancestor9'
if not os.path.exists(directory):
    os.makedirs(directory)

# pickle 파일 저장
file_path = os.path.join(directory, 'df.pickle')
with open(file_path, 'wb') as f:
    pickle.dump(df, f)

In [ ]:
# 디렉토리 생성
directory = 'ancestor8'
if not os.path.exists(directory):
    os.makedirs(directory)

In [ ]:
path = 'ancestor8/df.pickle'
df.to_pickle(path)

In [ ]:
df = pd.read_pickle(path)
df

,CustomerKey,Customer ID,Customer,City,State-Province,Country-Region,Postal Code
1,11000,AW00011000,Jon Yang,Rockhampton,Queensland,Australia,4700
2,11001,AW00011001,Eugene Huang,Seaford,Victoria,Australia,3198
3,11002,AW00011002,Ruben Torres,Hobart,Tasmania,Australia,7001
4,11003,AW00011003,Christy Zhu,North Ryde,New South Wales,Australia,2113
5,11004,AW00011004,Elizabeth Johnson,Wollongong,New South Wales,Australia,2500
...,...,...,...,...,...,...,...
18480,29479,AW00029479,Tommy Tang,Versailles,Yveline,France,78000
18481,29480,AW00029480,Nina Raji,London,England,United Kingdom,SW19 3RU
18482,29481,AW00029481,Ivan Suri,Hof,Bayern,Germany,95010
18483,29482,AW00029482,Clayton Zhang,Saint Ouen,Charente-Maritime,France,17490
18484,29483,AW00029483,Jésus Navarro,Paris La Defense,Hauts de Seine,France,92081

## 2. 기초정보 확인

In [ ]:
# prompt: df의 기초정보를 확인하려고 합니다. 다양한 명령어를 제시해 주세요.
# 각 명령어 자체도  text로 프린트해주고 명령어의 의미도 같이 해줘.
# 단 print(df.shape)형태 명령어는 사용하지 말고 df.shape로 해주세요

print("df.head(): 데이터프레임의 처음 5개 행을 출력합니다. 데이터의 일부를 확인하고 데이터의 형태를 파악하는데 유용합니다.")
df.head()

print("df.tail(): 데이터프레임의 마지막 5개 행을 출력합니다. 데이터의 일부를 확인하고 데이터의 형태를 파악하는데 유용합니다.")
df.tail()

print("df.info(): 데이터프레임의 각 열의 데이터 타입, null 값의 개수 등을 요약하여 출력합니다. 데이터의 구조와 결측치를 파악하는데 유용합니다.")
df.info()

print("df.describe(): 데이터프레임의 수치형 열에 대한 기술 통계량을 출력합니다. 평균, 표준편차, 최소값, 최대값, 사분위수 등을 확인하여 데이터의 분포를 파악하는데 유용합니다.")
df.describe()

print("df.columns: 데이터프레임의 열 이름을 출력합니다. 열 이름을 확인하고 데이터를 분석하는데 유용합니다.")
df.columns

print("df.dtypes: 데이터프레임의 각 열의 데이터 타입을 출력합니다. 데이터의 타입을 확인하고 필요에 따라 데이터 타입을 변경하는데 유용합니다.")
df.dtypes

print("df.shape: 데이터프레임의 행과 열의 수를 출력합니다. 데이터의 크기를 확인하고 데이터를 다루는 데 유용합니다.")
df.shape

print("df.isnull().sum(): 데이터프레임의 각 열의 null 값의 개수를 출력합니다. 결측치를 확인하고 처리하는데 유용합니다.")
df.isnull().sum()

print("df.nunique(): 데이터프레임의 각 열의 고유한 값의 개수를 출력합니다. 데이터의 다양성을 확인하는데 유용합니다.")
df.nunique()

df.head(): 데이터프레임의 처음 5개 행을 출력합니다. 데이터의 일부를 확인하고 데이터의 형태를 파악하는데 유용합니다.

,CustomerKey,Customer ID,Customer,City,State-Province,Country-Region,Postal Code
1,11000,AW00011000,Jon Yang,Rockhampton,Queensland,Australia,4700
2,11001,AW00011001,Eugene Huang,Seaford,Victoria,Australia,3198
3,11002,AW00011002,Ruben Torres,Hobart,Tasmania,Australia,7001
4,11003,AW00011003,Christy Zhu,North Ryde,New South Wales,Australia,2113
5,11004,AW00011004,Elizabeth Johnson,Wollongong,New South Wales,Australia,2500

df.tail(): 데이터프레임의 마지막 5개 행을 출력합니다. 데이터의 일부를 확인하고 데이터의 형태를 파악하는데 유용합니다.

,CustomerKey,Customer ID,Customer,City,State-Province,Country-Region,Postal Code
18480,29479,AW00029479,Tommy Tang,Versailles,Yveline,France,78000
18481,29480,AW00029480,Nina Raji,London,England,United Kingdom,SW19 3RU
18482,29481,AW00029481,Ivan Suri,Hof,Bayern,Germany,95010
18483,29482,AW00029482,Clayton Zhang,Saint Ouen,Charente-Maritime,France,17490
18484,29483,AW00029483,Jésus Navarro,Paris La Defense,Hauts de Seine,France,92081

df.info(): 데이터프레임의 각 열의 데이터 타입, null 값의 개수 등을 요약하여 출력합니다. 데이터의 구조와 결측치를 파악하는데 유용합니다.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18484 entries, 1 to 18484
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerKey     18484 non-null  int64
 1   Customer ID     18484 non-null  object
 2   Customer        18484 non-null  object
 3   City            18484 non-null  object
 4   State-Province  18484 non-null  object
 5   Country-Region  18484 non-null  object
 6   Postal Code     18484 non-null  object
dtypes: int64(1), object(6)
memory usage: 1011.0+ KB
df.describe(): 데이터프레임의 수치형 열에 대한 기술 통계량을 출력합니다. 평균, 표준편차, 최소값, 최대값, 사분위수 등을 확인하여 데이터의 분포를 파악하는데 유용합니다.

        CustomerKey
count  18484.000000
mean   20241.500000
std     5336.015523
min    11000.000000
25%    15620.750000
50%    20241.500000
75%    24862.250000
max    29483.000000

df.columns: 데이터프레임의 열 이름을 출력합니다. 열 이름을 확인하고 데이터를 분석하는데 유용합니다.

Index(['CustomerKey', 'Customer ID', 'Customer', 'City', 'State-Province',
       'Country-Region', 'Postal Code'],
      dtype='object')

df.dtypes: 데이터프레임의 각 열의 데이터 타입을 출력합니다. 데이터의 타입을 확인하고 필요에 따라 데이터 타입을 변경하는데 유용합니다.

CustomerKey        int64
Customer ID       object
Customer          object
City              object
State-Province    object
Country-Region    object
Postal Code       object
dtype: object

df.shape: 데이터프레임의 행과 열의 수를 출력합니다. 데이터의 크기를 확인하고 데이터를 다루는 데 유용합니다.

(18484, 7)

df.isnull().sum(): 데이터프레임의 각 열의 null 값의 개수를 출력합니다. 결측치를 확인하고 처리하는데 유용합니다.

CustomerKey       0
Customer ID       0
Customer          0
City              0
State-Province    0
Country-Region    0
Postal Code       0
dtype: int64

df.nunique(): 데이터프레임의 각 열의 고유한 값의 개수를 출력합니다. 데이터의 다양성을 확인하는데 유용합니다.

CustomerKey       18484
Customer ID       18484
Customer          18400
City                269
State-Province       53
Country-Region        6
Postal Code         323
dtype: int64

In [ ]:
df.columns

Index(['CustomerKey', 'Customer ID', 'Customer', 'City', 'State-Province',
       'Country-Region', 'Postal Code'],
      dtype='object')

In [ ]:
# prompt: df.columns, ['CustomerKey', 'Customer ID', 'Customer', 'City', 'State-Province',
#        'Country-Region', 'Postal Code']를 한글명으로 변경해줘

new_column_names = {
    'CustomerKey': '고객키',
    'Customer ID': '고객ID',
    'Customer': '고객명',
    'City': '도시',
    'State-Province': '주/지방',
    'Country-Region': '국가/지역',
    'Postal Code': '우편번호'
}

df = df.rename(columns=new_column_names)
df

         고객키   고객ID    고객명   도시  주/지방  국가/지역  우편번호
1      11000      0   9484  205    35      0    81
2      11001      1   6293  224    48      0    46
3      11002      2  15658  122    43      0   116
4      11003      3   3898  175    26      0    27
5      11004      4   5888  263    26      0    35
...      ...    ...    ...  ...   ...    ...   ...
18480  29479  18479  17474  249    52      2   136
18481  29480  18480  14174  148     8      4   284
18482  29481  18481   7890  123     3      3   210
18483  29482  18482   4024  214     7      2    18
18484  29483  18483  10091  191    14      2   178

[18484 rows x 7 columns]

In [ ]:
df['도시'].nunique()

269

In [ ]:
for col in df.columns:
    # print(col)
    print(f'컬럼명 {col} :  {df[col].nunique()}')

컬럼명 고객키 :  18484
컬럼명 고객ID :  18484
컬럼명 고객명 :  18400
컬럼명 도시 :  269
컬럼명 주/지방 :  53
컬럼명 국가/지역 :  6
컬럼명 우편번호 :  323

In [ ]:
# prompt: df 컬럼의 고유값, 결측치, 결측치 비율,  대표적인 값 5개만 보여주는 코드

for column in df.columns:
    print(f"Column: {column}")
    print(f"Unique values: {df[column].nunique()}")
    print(f"Missing values: {df[column].isnull().sum()}")
    print(f"Missing value ratio: {df[column].isnull().mean()}")
    print(f"Top 5 values: {df[column].value_counts().head(5)}")
    print("-" * 50)

Column: 고객키
Unique values: 18484
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 고객키
11000    1
23419    1
23327    1
23326    1
23325    1
Name: count, dtype: int64
--------------------------------------------------
Column: 고객ID
Unique values: 18484
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 고객ID
AW00011000    1
AW00023419    1
AW00023327    1
AW00023326    1
AW00023325    1
Name: count, dtype: int64
--------------------------------------------------
Column: 고객명
Unique values: 18400
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 고객명
Mohamed Pal       3
Jordan Roberts    2
Alexandra Hall    2
Gilbert Xu        2
Richard Blue      2
Name: count, dtype: int64
--------------------------------------------------
Column: 도시
Unique values: 269
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 도시
London       420
Paris        386
Burien       212
Concord      212
Beaverton    210
Name: count, dtype: int64
--------------------------------------------------
Column: 주/지방
Unique values: 53
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 주/지방
California          4444
Washington          2263
England             1913
New South Wales     1559
British Columbia    1559
Name: count, dtype: int64
--------------------------------------------------
Column: 국가/지역
Unique values: 6
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 국가/지역
United States     7819
Australia         3591
United Kingdom    1913
France            1810
Germany           1780
Name: count, dtype: int64
--------------------------------------------------
Column: 우편번호
Unique values: 323
Missing values: 0
Missing value ratio: 0.0
Top 5 values: 우편번호
98168    212
94519    212
98225    210
97005    210
91910    206
Name: count, dtype: int64
--------------------------------------------------

In [ ]:
# prompt: for column in df.columns:
#     print(f"Column: {column}")
#     print(f"Unique values: {df[column].nunique()}")
#     print(f"Missing values: {df[column].isnull().sum()}")
#     print(f"Missing value ratio: {df[column].isnull().mean()}")
#     print(f"Top 5 values: {df[column].value_counts().head(5)}")
#     print("-" * 50)
# 이 모든 정보를 일목요연하게 한 번에 보는 방법

import pandas as pd
def column_info(df):
  """
  데이터프레임의 각 열에 대한 정보를 요약하여 출력합니다.

  Args:
    df: pandas DataFrame
  """
  info_dict = {}
  for column in df.columns:
    info_dict[column] = {
        'Unique values': df[column].nunique(),
        'Missing values': df[column].isnull().sum(),
        'Missing value ratio': df[column].isnull().mean(),
        'Top 5 values': df[column].value_counts().head(5).to_dict()
    }
  return pd.DataFrame(info_dict)


column_info_df = column_info(df)
column_info_df

,고객키,고객ID,고객명,도시,주/지방,국가/지역,우편번호
Unique values,18484,18484,18400,269,53,6,323
Missing values,0,0,0,0,0,0,0
Missing value ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Top 5 values,"{11000: 1, 23419: 1, 23327: 1, 23326: 1, 23325...","{'AW00011000': 1, 'AW00023419': 1, 'AW00023327...","{'Mohamed Pal': 3, 'Jordan Roberts': 2, 'Alexa...","{'London': 420, 'Paris': 386, 'Burien': 212, '...","{'California': 4444, 'Washington': 2263, 'Engl...","{'United States': 7819, 'Australia': 3591, 'Un...","{'98168': 212, '94519': 212, '98225': 210, '97..."

In [ ]:
# prompt: column_info_df 코드를 아주 간단하게 만들어줘

import pandas as pd
def column_info(df):
  return pd.DataFrame({
      col: {
          'Unique values': df[col].nunique(),
          'Missing values': df[col].isnull().sum(),
          'Missing value ratio': df[col].isnull().mean(),
          'Top 5 values': df[col].value_counts().head(5).to_dict()
      } for col in df.columns
  })

column_info_df = column_info(df)
column_info_df

,고객키,고객ID,고객명,도시,주/지방,국가/지역,우편번호
Unique values,18484,18484,18400,269,53,6,323
Missing values,0,0,0,0,0,0,0
Missing value ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Top 5 values,"{11000: 1, 23419: 1, 23327: 1, 23326: 1, 23325...","{'AW00011000': 1, 'AW00023419': 1, 'AW00023327...","{'Mohamed Pal': 3, 'Jordan Roberts': 2, 'Alexa...","{'London': 420, 'Paris': 386, 'Burien': 212, '...","{'California': 4444, 'Washington': 2263, 'Engl...","{'United States': 7819, 'Australia': 3591, 'Un...","{'98168': 212, '94519': 212, '98225': 210, '97..."

In [ ]:
# prompt: column_info_df의 가로와 세로를 전환해줘

column_info_df.transpose()

,Unique values,Missing values,Missing value ratio,Top 5 values
고객키,18484,0,0.0,"{11000: 1, 23419: 1, 23327: 1, 23326: 1, 23325..."
고객ID,18484,0,0.0,"{'AW00011000': 1, 'AW00023419': 1, 'AW00023327..."
고객명,18400,0,0.0,"{'Mohamed Pal': 3, 'Jordan Roberts': 2, 'Alexa..."
도시,269,0,0.0,"{'London': 420, 'Paris': 386, 'Burien': 212, '..."
주/지방,53,0,0.0,"{'California': 4444, 'Washington': 2263, 'Engl..."
국가/지역,6,0,0.0,"{'United States': 7819, 'Australia': 3591, 'Un..."
우편번호,323,0,0.0,"{'98168': 212, '94519': 212, '98225': 210, '97..."

In [ ]:
# prompt: 고객키 컬럼에 100개의 값에 np.nan을 만들어줘

import numpy as np

# 고객키 컬럼에 100개의 값에 np.nan을 할당합니다.
df.loc[:99, '고객키'] = np.nan

In [ ]:
import numpy as np
np.nan

nan

In [ ]:
df.loc[:19999, '고객키'] = np.nan

In [ ]:
df.isnull().sum()/len(df)*100
df.isnull().sum()/df.shape[0]*100

고객키      100.0
고객ID       0.0
고객명        0.0
도시         0.0
주/지방       0.0
국가/지역      0.0
우편번호       0.0
dtype: float64

고객키      100.0
고객ID       0.0
고객명        0.0
도시         0.0
주/지방       0.0
국가/지역      0.0
우편번호       0.0
dtype: float64

In [ ]:
# prompt: 국가/지역별로 그룹핑한 통계를 보고 싶다

grouped_df = df.groupby('국가/지역').agg({
    '고객키': 'count',  # 고객 수 계산
    # 필요에 따라 다른 열에 대한 통계 추가
})
grouped_df

                 고객키
국가/지역
Australia       3591
Canada          1571
France          1810
Germany         1780
United Kingdom  1913
United States   7819

In [ ]:
df['국가/지역'].value_counts()

국가/지역
United States     7819
Australia         3591
United Kingdom    1913
France            1810
Germany           1780
Canada            1571
Name: count, dtype: int64

In [ ]:
# prompt: df['국가/지역'].value_counts(), 오른차순으로

df['국가/지역'].value_counts().sort_values(ascending=True)

국가/지역
Canada            1571
Germany           1780
France            1810
United Kingdom    1913
Australia         3591
United States     7819
Name: count, dtype: int64

In [ ]:
# prompt: 모든 컬럼의 value_count()를 보려고 한다

for column in df.columns:
  print(f"Column: {column}")
  df[column].value_counts()
  print("-" * 50)

Column: 고객키

고객키
11000    1
23419    1
23327    1
23326    1
23325    1
        ..
17160    1
17159    1
17158    1
17157    1
29483    1
Name: count, Length: 18484, dtype: int64

--------------------------------------------------
Column: 고객ID

고객ID
AW00011000    1
AW00023419    1
AW00023327    1
AW00023326    1
AW00023325    1
             ..
AW00017160    1
AW00017159    1
AW00017158    1
AW00017157    1
AW00029483    1
Name: count, Length: 18484, dtype: int64

--------------------------------------------------
Column: 고객명

고객명
Mohamed Pal        3
Jordan Roberts     2
Alexandra Hall     2
Gilbert Xu         2
Richard Blue       2
                  ..
Jasmine James      1
Katherine Clark    1
Jesse Adams        1
David Bryant       1
Jésus Navarro      1
Name: count, Length: 18400, dtype: int64

--------------------------------------------------
Column: 도시

도시
London          420
Paris           386
Burien          212
Concord         212
Beaverton       210
               ...
Carol Stream      1
Byron             1
Chehalis          1
Chantilly         1
Bountiful         1
Name: count, Length: 269, dtype: int64

--------------------------------------------------
Column: 주/지방

주/지방
California             4444
Washington             2263
England                1913
New South Wales        1559
British Columbia       1559
Oregon                 1073
Victoria                894
Queensland              793
Saarland                442
Nordrhein-Westfalen     406
Seine (Paris)           386
Hessen                  377
Hamburg                 297
Seine Saint Denis       285
Nord                    284
South Australia         239
Bayern                  228
Hauts de Seine          195
Yveline                 168
Essonne                 150
Tasmania                106
Seine et Marne           60
Loiret                   60
Moselle                  56
Val d'Oise               30
Garonne (Haute)          30
Brandenburg              30
Val de Marne             30
Somme                    22
Charente-Maritime        21
Loir et Cher             17
Pas de Calais            16
Alberta                  11
Illinois                  6
Ohio                      4
Texas                     4
Georgia                   3
New York                  3
Florida                   3
Arizona                   2
Utah                      2
Wyoming                   2
Minnesota                 1
Missouri                  1
Kentucky                  1
South Carolina            1
North Carolina            1
Virginia                  1
Ontario                   1
Mississippi               1
Montana                   1
Massachusetts             1
Alabama                   1
Name: count, dtype: int64

--------------------------------------------------
Column: 국가/지역

국가/지역
United States     7819
Australia         3591
United Kingdom    1913
France            1810
Germany           1780
Canada            1571
Name: count, dtype: int64

--------------------------------------------------
Column: 우편번호

우편번호
98168    212
94519    212
98225    210
97005    210
91910    206
        ...
60188      1
31008      1
98532      1
20151      1
84010      1
Name: count, Length: 323, dtype: int64

--------------------------------------------------

In [ ]:
df.groupby(['국가/지역'])['도시'].count()

국가/지역
Australia         3591
Canada            1571
France            1810
Germany           1780
United Kingdom    1913
United States     7819
Name: 도시, dtype: int64

In [ ]:
# 국가/지역별 고객 수를 계산하고, unstack을 사용하여 표 형태로 변환
grouped_df = df.groupby(['국가/지역', '도시'])['고객키'].count().unstack()
grouped_df

도시,Ballard,Barstow,Basingstoke Hants,Baytown,Beaverton,Bell Gardens,Bellevue,Bellflower,Bellingham,Bendigo,...,West Covina,West Sussex,Westminster,Wokingham,Wollongong,Woodburn,Woodland Hills,Woolston,Yakima,York
국가/지역,,,,,,,,,,,,,,,,,,,,,
Australia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104.0,...,NaN,NaN,NaN,NaN,105.0,NaN,NaN,NaN,NaN,NaN
Canada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,92.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Germany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
United Kingdom,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,30.0,NaN,30.0,NaN,NaN,NaN,30.0,NaN,115.0
United States,68.0,1.0,NaN,1.0,210.0,1.0,1.0,194.0,210.0,NaN,...,87.0,NaN,NaN,NaN,NaN,90.0,96.0,NaN,96.0,NaN

In [ ]:
df.head()

,고객키,고객ID,고객명,도시,주/지방,국가/지역,우편번호
1,11000,AW00011000,Jon Yang,Rockhampton,Queensland,Australia,4700
2,11001,AW00011001,Eugene Huang,Seaford,Victoria,Australia,3198
3,11002,AW00011002,Ruben Torres,Hobart,Tasmania,Australia,7001
4,11003,AW00011003,Christy Zhu,North Ryde,New South Wales,Australia,2113
5,11004,AW00011004,Elizabeth Johnson,Wollongong,New South Wales,Australia,2500

In [ ]:
grouped_df = df.groupby(['국가/지역'])['도시'].count()
grouped_df

국가/지역
Australia         3591
Canada            1571
France            1810
Germany           1780
United Kingdom    1913
United States     7819
Name: 도시, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18484 entries, 1 to 18484
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객키     18484 non-null  int64
 1   고객ID    18484 non-null  object
 2   고객명     18484 non-null  object
 3   도시      18484 non-null  object
 4   주/지방    18484 non-null  object
 5   국가/지역   18484 non-null  object
 6   우편번호    18484 non-null  object
dtypes: int64(1), object(6)
memory usage: 1011.0+ KB

In [ ]:
# prompt: df의 object 자료형을 category형태로 변경

for column in df.columns:
  if df[column].dtype == 'object':
    df[column] = df[column].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18484 entries, 1 to 18484
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객키     18484 non-null  int64
 1   고객ID    18484 non-null  category
 2   고객명     18484 non-null  category
 3   도시      18484 non-null  category
 4   주/지방    18484 non-null  category
 5   국가/지역   18484 non-null  category
 6   우편번호    18484 non-null  category
dtypes: category(6), int64(1)
memory usage: 1.6 MB

In [ ]:
# prompt: df의 범주형데이터를 수치형으로 전환

from sklearn.preprocessing import LabelEncoder

# 범주형 데이터를 수치형으로 변환
le = LabelEncoder()
for column in df.columns:
    if df[column].dtype == 'category':
        df[column] = le.fit_transform(df[column])

df.head()

     고객키  고객ID    고객명   도시  주/지방  국가/지역  우편번호
1  11000     0   9484  205    35      0    81
2  11001     1   6293  224    48      0    46
3  11002     2  15658  122    43      0   116
4  11003     3   3898  175    26      0    27
5  11004     4   5888  263    26      0    35

In [ ]:
tf = df.sample(100)
tf

         고객키   고객ID    고객명   도시  주/지방  국가/지역  우편번호
13159  24158  13158  14335  145    28      2    89
17632  28631  17631   7857  168     5      1   302
2819   13818   2818   4856   92    38      2   194
17904  28903  17903  10220  148     8      4   281
11402  22401  11401   7617  205    35      0    81
...      ...    ...    ...  ...   ...    ...   ...
17680  28679  17679   9962  216    33      5   222
14467  25466  14466   8435  215    38      2   192
10146  21145  10145  13471   37     6      5   195
9266   20265   9265   3936  120    35      0    80
273    11272    272  11466   14     6      5   151

[100 rows x 7 columns]

In [ ]:
tf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 13159 to 273
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   고객키     100 non-null    int64
 1   고객ID    100 non-null    int64
 2   고객명     100 non-null    int64
 3   도시      100 non-null    int64
 4   주/지방    100 non-null    int64
 5   국가/지역   100 non-null    int64
 6   우편번호    100 non-null    int64
dtypes: int64(7)
memory usage: 6.2 KB

# TIP데이터로 문제내기